import type { Project } from "./types";

export const PROJECTS: Project[] = [
  {
    id: "alexendros-me",
    title: "alexendros.me — Sitio personal",
    category: "Web",
    kind: "Web App",
    year: "2026",
    h: 185,
    featured: true,
    image: "/proyectos/alexendros-me.png",
    tags: ["Next.js", "React", "TypeScript", "Tailwind", "Vercel"],
    desc: "Sitio web para publicar ideas, rápido y respetuoso con la privacidad: sin rastreo ni cookies de terceros. Construido con Next.js y React, con tipografía propia y servido desde la red global de Vercel para que cargue al instante.",
    metaDescription: "Sitio personal en Next.js sin rastreo ni cookies. Rápido, privado y construido con React, Tailwind y Vercel.",
    liveUrl: "https://alexendros.me",
    metrics: [
      { v: "0", l: "rastreadores / cookies", acc: true },
      { v: "Next.js", l: "React + Tailwind" },
      { v: "100%", l: "carga instantánea" },
    ],
  },
  {
    id: "nasve",
    title: "Gráficas Nasve — Web y tienda para imprenta",
    category: "Web",
    kind: "Web App",
    year: "2026",
    h: 210,
    featured: true,
    image: "/proyectos/nasve.png",
    tags: ["Next.js", "React", "TypeScript", "E-commerce", "Vercel"],
    desc: "Sitio web y tienda para Gráficas Nasve, imprenta familiar de Torrent desde 1982: catálogo, configurador de encargos y solicitud de presupuesto, con un diseño a medida que transmite oficio y confianza. Proyecto de cliente, de la idea al lanzamiento.",
    metaDescription: "Web y tienda a medida para Gráficas Nasve (imprenta, Torrent 1982): catálogo, configurador de encargos y presupuesto.",
    liveUrl: "https://ecommerce-graficasnasve.vercel.app",
    metrics: [
      { v: "Web + tienda", l: "diseño y desarrollo", acc: true },
      { v: "Next.js", l: "React + TypeScript" },
      { v: "2026", l: "proyecto de cliente" },
    ],
  },
  {
    id: "pipeline-crm",
    title: "Pipeline CRM + Notion — Automatización de ventas",
    category: "Automatización",
    kind: "Plataforma",
    year: "2026",
    h: 220,
    featured: true,
    tags: ["Next.js", "Prisma", "Stripe", "Notion API", "REST"],
    desc: "Pipeline de ventas con 9 etapas, API CRM REST (8 handlers), webhook ampliado de Stripe y sincronización bidireccional con Notion. 188 tests de integración.",
    metrics: [
      { v: "9", l: "etapas pipeline" },
      { v: "188", l: "tests integración", acc: true },
      { v: "bidireccional", l: "sync Notion" },
    ],
    repoUrl: "https://github.com/Iniciativas-Alexendros/website-alexendrosdev",
    liveUrl: "https://alexendros.dev/servicios",
  },
  {
    id: "stripe-catalog",
    title: "Catálogo unificado + Stripe Checkout",
    category: "E-commerce",
    kind: "API",
    year: "2026",
    h: 200,
    tags: ["Stripe", "Next.js", "TypeScript", "Zod"],
    desc: "Sistema de catálogo server-trusted con checkout Stripe unificado (suscripción y one-time), precios en céntimos, doble canal de pago y webhook de verificación de firma.",
    metrics: [
      { v: "10", l: "tests unitarios" },
      { v: "2", l: "canales de pago", acc: true },
      { v: "server-trusted", l: "catálogo" },
    ],
    repoUrl: "https://github.com/Iniciativas-Alexendros/website-alexendrosdev",
  },
  {
    id: "mcp-toolkit",
    title: "MCP Toolkit — Servidores para agentes IA",
    category: "Developer Tooling",
    kind: "Open Source",
    year: "2026",
    h: 210,
    tags: ["MCP", "TypeScript", "Rust", "Zod"],
    desc: "Colección de servidores MCP listos para producción: custodia de credenciales, acceso a APIs externas y herramientas de desarrollo para agentes de IA. Tipado estricto y tests.",
    metrics: [
      { v: "MCP", l: "protocolo estándar" },
      { v: "AGPL-3.0", l: "open source", acc: true },
      { v: "multi-lang", l: "TS + Rust" },
    ],
    repoUrl: "https://github.com/Alexendros",
  },
];

export function getProject(id: string): Project | undefined {
  return PROJECTS.find((p) => p.id === id);
}
