allowBuilds:
  sharp: true
  unrs-resolver: true
  "@tailwindcss/oxide": true
  "@prisma/engines": true
  prisma: true
  "@prisma/client": true
  msw: false
  "@google/genai": true
  protobufjs: true
