name: Lighthouse
on:
  deployment_status:

permissions:
  contents: read
  # Necesario para subir artefactos de Lighthouse a GitHub.
  checks: write

jobs:
  lighthouse:
    if: >-
      github.event.deployment_status.state == 'success' &&
      (
        github.event.deployment_status.environment == 'Preview' ||
        github.event.deployment_status.environment == 'Production'
      )
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Lighthouse CI
        uses: treosh/lighthouse-ci-action@3e7e23fb74242897f95c0ba9cabad3d0227b9b18 # v12.6.2
        with:
          urls: ${{ github.event.deployment_status.target_url }}
          budgetPath: .github/lighthouse-budget.json
          uploadArtifacts: true
          temporaryPublicStorage: true
